"""add article table with pgvector

Revision ID: 81badef090c0
Revises: f81be53de77c
Create Date: 2023-11-01 21:40:15.365004

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "81badef090c0"
down_revision = "f81be53de77c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "factors", pgvector.sqlalchemy.Vector(dim=20), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("article")
    # ### end Alembic commands ###
