version: "3.9"
networks:
  net:
    driver: bridge
services:
  oauth:
    image: ghcr.io/navikt/mock-oauth2-server:2.0.0
    container_name: oauth
    ports:
      - "8002:8080"
    volumes:
      - "./src/docker/oauth2:/conf"
    environment:
      - JSON_CONFIG_PATH=/conf/OAuth2Config.json
    networks:
      - net
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      # - PGDATA=/var/lib/postgresql/data/
    # volumes:
    #   - "./src/sql/init.sql:/docker-entrypoint-initdb.d/"
    ports:
      - '5432:5432'
    networks:
      - net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WITHIN_DOCKER_ENV: 1
      DB_URL: "postgresql://postgres:postgres@db/postgres"
    ports:
      - 4555:80
    networks:
      - net
    depends_on:
      - db
      - oauth
