version: "3.9"
networks:
  net:
    driver: bridge
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      # - PGDATA=/var/lib/postgresql/data/
    # volumes:
    #   - ./mock_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WITHIN_DOCKER_ENV: 1
    ports:
      - 4555:80
    networks:
      - net
